Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "GCC/4.9.3-2.25", "GCCcore/4.9.3"

   Try: "module spider GCC/4.9.3-2.25 GCCcore/4.9.3" to see how to load the
module(s).




Requirement already satisfied: numpy in /home/s3801128/.local/lib/python2.7/site-packages
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /data/s3801128/retinanet/keras-retinanet
Collecting keras (from keras-retinanet==0.5.0)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl (312kB)
Collecting keras-resnet (from keras-retinanet==0.5.0)
  Downloading https://files.pythonhosted.org/packages/05/46/ad0b2d1a05d9497bd80c98a2c3f4d8be38a4601ace69af72814f5fafd851/keras-resnet-0.1.0.tar.gz
Requirement already satisfied: six in /apps/haswell/software/Python/2.7.14-fosscuda-2018a/lib/python2.7/site-packages/six-1.11.0-py2.7.egg (from keras-retinanet==0.5.0)
Requirement already satisfied: scipy in /apps/haswell/software/Python/2.7.14-fosscuda-2018a/lib/python2.7/site-packages/scipy-1.0.0-py2.7-linux-x86_64.egg (from keras-retinanet==0.5.0)
Requirement already satisfied: cython in /apps/haswell/software/Python/2.7.14-fosscuda-2018a/lib/python2.7/site-packages/Cython-0.27.3-py2.7-linux-x86_64.egg (from keras-retinanet==0.5.0)
Collecting Pillow (from keras-retinanet==0.5.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/0d/f3/421598450cb9503f4565d936860763b5af413a61009d87a5ab1e34139672/Pillow-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
Collecting opencv-python (from keras-retinanet==0.5.0)
  Downloading https://files.pythonhosted.org/packages/e8/04/925d40d1aca43b949453c9350345ac0b4ca122d479d6d254a54ad0d1dd23/opencv_python-4.0.0.21-cp27-cp27mu-manylinux1_x86_64.whl (25.4MB)
Collecting progressbar2 (from keras-retinanet==0.5.0)
  Downloading https://files.pythonhosted.org/packages/0c/78/0ae9129f12098adbcfee0c51a81dfa94cdc1853142aa4d62e63c6a355bd7/progressbar2-3.39.2-py2.py3-none-any.whl
Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/s3801128/.local/lib/python2.7/site-packages (from keras->keras-retinanet==0.5.0)
Requirement already satisfied: numpy>=1.9.1 in /home/s3801128/.local/lib/python2.7/site-packages (from keras->keras-retinanet==0.5.0)
Collecting pyyaml (from keras->keras-retinanet==0.5.0)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Requirement already satisfied: h5py in /home/s3801128/.local/lib/python2.7/site-packages (from keras->keras-retinanet==0.5.0)
Requirement already satisfied: keras-applications>=1.0.6 in /home/s3801128/.local/lib/python2.7/site-packages (from keras->keras-retinanet==0.5.0)
Collecting python-utils>=2.3.0 (from progressbar2->keras-retinanet==0.5.0)
  Downloading https://files.pythonhosted.org/packages/eb/a0/19119d8b7c05be49baf6c593f11c432d571b70d805f2fe94c0585e55e4c8/python_utils-2.3.0-py2.py3-none-any.whl
Building wheels for collected packages: keras-retinanet, keras-resnet, pyyaml
  Running setup.py bdist_wheel for keras-retinanet: started
  Running setup.py bdist_wheel for keras-retinanet: finished with status 'done'
  Stored in directory: /home/s3801128/.cache/pip/wheels/a3/05/76/cfd7e1f93ed2b042b6f9958cba0e16972600df08d4509589b8
  Running setup.py bdist_wheel for keras-resnet: started
  Running setup.py bdist_wheel for keras-resnet: finished with status 'done'
  Stored in directory: /home/s3801128/.cache/pip/wheels/80/dd/ac/842235b63dddac12faa4b48ebe58b8944e8c2e57c2e38dddb6
  Running setup.py bdist_wheel for pyyaml: started
  Running setup.py bdist_wheel for pyyaml: finished with status 'done'
  Stored in directory: /home/s3801128/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
Successfully built keras-retinanet keras-resnet pyyaml
Installing collected packages: pyyaml, keras, keras-resnet, Pillow, opencv-python, python-utils, progressbar2, keras-retinanet
Successfully installed Pillow-5.4.1 keras-2.2.4 keras-resnet-0.1.0 keras-retinanet-0.5.0 opencv-python-4.0.0.21 progressbar2-3.39.2 python-utils-2.3.0 pyyaml-3.13
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: tensorflow-gpu in /home/s3801128/.local/lib/python2.7/site-packages
Requirement already satisfied: astor>=0.6.0 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: gast>=0.2.0 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: enum34>=1.1.6 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: protobuf>=3.6.1 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: six>=1.10.0 in /apps/haswell/software/Python/2.7.14-fosscuda-2018a/lib/python2.7/site-packages/six-1.11.0-py2.7.egg (from tensorflow-gpu)
Requirement already satisfied: absl-py>=0.1.6 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: backports.weakref>=1.0rc1 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: wheel in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: termcolor>=1.1.0 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: tensorboard<1.13.0,>=1.12.0 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: numpy>=1.13.3 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: mock>=2.0.0 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: keras-applications>=1.0.6 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: grpcio>=1.8.6 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorflow-gpu)
Requirement already satisfied: setuptools in /apps/haswell/software/Python/2.7.14-fosscuda-2018a/lib/python2.7/site-packages/setuptools-38.4.0-py2.7.egg (from protobuf>=3.6.1->tensorflow-gpu)
Requirement already satisfied: markdown>=2.6.8 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu)
Requirement already satisfied: futures>=3.1.1; python_version < "3" in /home/s3801128/.local/lib/python2.7/site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu)
Requirement already satisfied: werkzeug>=0.11.10 in /home/s3801128/.local/lib/python2.7/site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /home/s3801128/.local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu)
Requirement already satisfied: pbr>=0.11 in /apps/haswell/software/Python/2.7.14-fosscuda-2018a/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu)
Requirement already satisfied: h5py in /home/s3801128/.local/lib/python2.7/site-packages (from keras-applications>=1.0.6->tensorflow-gpu)
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/s3801128/.local/bin/retinanet-train", line 7, in <module>
    from keras_retinanet.bin.train import main
  File "/home/s3801128/.local/lib/python2.7/site-packages/keras_retinanet/bin/train.py", line 24, in <module>
    import keras
  File "/home/s3801128/.local/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/s3801128/.local/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/s3801128/.local/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/s3801128/.local/lib/python2.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/s3801128/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/s3801128/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/s3801128/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/s3801128/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/s3801128/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/s3801128/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/s3801128/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


###############################################################################
Peregrine Cluster
Job 3343343 for user 's3801128'
Finished at: Mon Jan 14 01:31:34 CET 2019

Job details:
============

Name                : Train retinanet multi gpu vgg backbone 500 batch size
User                : s3801128
Partition           : gpu
Nodes               : pg-gpu03
Cores               : 12
State               : FAILED
Submit              : 2019-01-13T23:15:13
Start               : 2019-01-14T01:30:58
End                 : 2019-01-14T01:31:34
Reserved walltime   : 00:30:00
Used walltime       : 00:00:36
Used CPU time       : 00:32:26 (efficiency: 450.66%)
% User (Computation): 60.05%
% System (I/O)      : 39.95%
Mem reserved        : 8G/node
Max Mem used        : 74.53M (pg-gpu03)
Max Disk Write      : 204.80K (pg-gpu03)
Max Disk Read       : 15.87M (pg-gpu03)


Acknowledgements:
=================

Please see this page if you want to acknowledge Peregrine in your publications:

https://redmine.hpc.rug.nl/redmine/projects/peregrine/wiki/ScientificOutput

################################################################################
