Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "GCCcore/4.9.3"

   Try: "module spider GCCcore/4.9.3" to see how to load the module(s).




Collecting h5py (from -r requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/30/99/d7d4fbf2d02bb30fb76179911a250074b55b852d34e98dd452a9f394ac06/h5py-2.9.0-cp36-cp36m-manylinux1_x86_64.whl (2.8MB)
Collecting Keras==2.0.3 (from -r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/1b/36/fc4b247ec139ad9cc6f223ed10729d85401fc5203703c23457794f9bfe60/Keras-2.0.3.tar.gz (196kB)
Requirement already satisfied: numpy in /apps/haswell/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/numpy-1.14.0-py3.6-linux-x86_64.egg (from -r requirements.txt (line 3))
Collecting opencv-python (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/37/49/874d119948a5a084a7ebe98308214098ef3471d76ab74200f9800efeef15/opencv_python-4.0.0.21-cp36-cp36m-manylinux1_x86_64.whl (25.4MB)
Collecting sklearn (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Requirement already satisfied: six in /apps/haswell/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/six-1.11.0-py3.6.egg (from h5py->-r requirements.txt (line 1))
Collecting theano (from Keras==2.0.3->-r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/4d/b1/d490d88ab47f01f367f413bd2e47d86acf92c84157c5172c23903798bd70/Theano-1.0.3.tar.gz (2.8MB)
Collecting pyyaml (from Keras==2.0.3->-r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Collecting scikit-learn (from sklearn->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/0d/3a/b92670f5c368c20329ecc4c255993fae7934564d485c3ed7ea7b8da7f741/scikit_learn-0.20.2-cp36-cp36m-manylinux1_x86_64.whl (5.4MB)
Requirement already satisfied: scipy>=0.14 in /apps/haswell/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/scipy-1.0.0-py3.6-linux-x86_64.egg (from theano->Keras==2.0.3->-r requirements.txt (line 2))
Installing collected packages: h5py, theano, pyyaml, Keras, opencv-python, scikit-learn, sklearn
  Running setup.py install for theano: started
    Running setup.py install for theano: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
  Running setup.py install for Keras: started
    Running setup.py install for Keras: finished with status 'done'
  Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'
Successfully installed Keras-2.0.3 h5py-2.9.0 opencv-python-4.0.0.21 pyyaml-3.13 scikit-learn-0.20.2 sklearn-0.0 theano-1.0.3
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_frcnn.py", line 10, in <module>
    from keras import backend as K
  File "/home/s3801128/.local/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/home/s3801128/.local/lib/python3.6/site-packages/keras/activations.py", line 3, in <module>
    from . import backend as K
  File "/home/s3801128/.local/lib/python3.6/site-packages/keras/backend/__init__.py", line 73, in <module>
    from .tensorflow_backend import *
  File "/home/s3801128/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'


###############################################################################
Peregrine Cluster
Job 3329611 for user 's3801128'
Finished at: Thu Jan 10 20:29:43 CET 2019

Job details:
============

Name                : Train tf FRCNN Keras model with only bp data resnet50 as backbone not training shared layers
User                : s3801128
Partition           : regular
Nodes               : pg-node108
Cores               : 1
State               : FAILED
Submit              : 2019-01-10T20:28:54
Start               : 2019-01-10T20:28:54
End                 : 2019-01-10T20:29:43
Reserved walltime   : 12:00:00
Used walltime       : 00:00:49
Used CPU time       : 00:20:31 (efficiency: 2512.98%)
% User (Computation): 80.79%
% System (I/O)      : 19.21%
Mem reserved        : 8G/node
Max Mem used        : 96.99M (pg-node108)
Max Disk Write      : 71.68K (pg-node108)
Max Disk Read       : 7.16M (pg-node108)


Acknowledgements:
=================

Please see this page if you want to acknowledge Peregrine in your publications:

https://redmine.hpc.rug.nl/redmine/projects/peregrine/wiki/ScientificOutput

################################################################################
